version: "0.2"
ignorePaths:
  - pnpm-lock.yaml
dictionaryDefinitions: []
dictionaries: []
words:
  - astrojs
  - daisyui
  - defu
  - heroicons
  - iconify
  - importantimport
  - koimi
  - tsconfigs
  - urara
ignoreWords: []
import: []
